<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaMiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('siswas_mi')->insert([
            // =================== KELAS 1 (2025) ===================
            [
                'nama' => 'Ameera Dhania Putri',
                'nisn' => '2025001001',
                'tahun' => 2025,
                'no_hp_wali' => '081231112201',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 12, RT 02 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Sri Wahyuni Astutik',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'Kirana Nailul Muna',
                'nisn' => '2025001002',
                'tahun' => 2025,
                'no_hp_wali' => '081231112202',
                'alamat_siswa' => 'Jl. Nyamplungan No. 45, RT 01 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Eko Budi Santoso',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'Maheer Zain Arifin',
                'nisn' => '2025001003',
                'tahun' => 2025,
                'no_hp_wali' => '081231112203',
                'alamat_siswa' => 'Jl. Sasak No. 7, RT 03 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ahmad Choirul Anwar',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'Muhammad Thoriq Alfarizi',
                'nisn' => '2025001004',
                'tahun' => 2025,
                'no_hp_wali' => '081231112204',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 33, RT 04 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Lilis Kartikasari',
                'kelas_id' => 1,
            ],

            // =================== KELAS 2 (2024) ===================
            [
                'nama' => 'Zafira Riskya Syabani',
                'nisn' => '2024202001',
                'tahun' => 2024,
                'no_hp_wali' => '081231112205',
                'alamat_siswa' => 'Jl. Ampel Suci No. 19, RT 05 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rizky Dwi Prasetyo',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'Alisha Sofia Ariztha',
                'nisn' => '2024202002',
                'tahun' => 2024,
                'no_hp_wali' => '081231112206',
                'alamat_siswa' => 'Jl. Petukangan No. 28, RT 03 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Dewi Kartika Sari',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'Abqori Fastabiqul Khoirot',
                'nisn' => '2024202003',
                'tahun' => 2024,
                'no_hp_wali' => '081231112207',
                'alamat_siswa' => 'Jl. Sidotopo No. 55, RT 06 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Sugeng Hariyanto',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'Arsyilla Farzana Azkadina',
                'nisn' => '2024202004',
                'tahun' => 2024,
                'no_hp_wali' => '081231112208',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 16, RT 02 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Siti Maemunah Uswatun',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'Izmy Aisyah Fachrudinsyah',
                'nisn' => '2024202005',
                'tahun' => 2024,
                'no_hp_wali' => '081231112209',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 77, RT 04 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Hendra Wicaksono',
                'kelas_id' => 2,
            ],

            // =================== KELAS 3 (2023) ===================
            [
                'nama' => 'Fahmi Ammar Ramadhan',
                'nisn' => '2023203001',
                'tahun' => 2023,
                'no_hp_wali' => '081231112210',
                'alamat_siswa' => 'Jl. Nyamplungan Gg 3 No. 5, RT 03 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Bagus Setiawan Saputra',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Nabil Fuady',
                'nisn' => '2023203002',
                'tahun' => 2023,
                'no_hp_wali' => '081231112211',
                'alamat_siswa' => 'Jl. Sasak No. 44, RT 06 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Dian Purnama Sari',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Nabila Mustofa Aidid',
                'nisn' => '2023203003',
                'tahun' => 2023,
                'no_hp_wali' => '081231112212',
                'alamat_siswa' => 'Jl. Gubah No. 23, RT 01 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ahmad Zainul Fikri',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Najwa',
                'nisn' => '2023203004',
                'tahun' => 2023,
                'no_hp_wali' => '081231112213',
                'alamat_siswa' => 'Jl. Ampel Lonceng No. 18, RT 05 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nurul Sulastri Handayani',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Sahnaz Banin',
                'nisn' => '2023203005',
                'tahun' => 2023,
                'no_hp_wali' => '081231112214',
                'alamat_siswa' => 'Jl. Petukangan No. 66, RT 07 / RW 08, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ari Kurniawan Prabowo',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Sultan Ramadhan Sava Hidayat',
                'nisn' => '2023203006',
                'tahun' => 2023,
                'no_hp_wali' => '081231112215',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 29, RT 03 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rendy Suharto Putra',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Syaqila Afrizani Zemira',
                'nisn' => '2023203007',
                'tahun' => 2023,
                'no_hp_wali' => '081231112216',
                'alamat_siswa' => 'Jl. Nyamplungan No. 58, RT 02 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Mega Listyaningrum',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Hasani Hasan Nawawi',
                'nisn' => '2023203008',
                'tahun' => 2023,
                'no_hp_wali' => '081231112217',
                'alamat_siswa' => 'Jl. Ampel Suci No. 42, RT 05 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Budi Santika Raharjo',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'Syiha Asyifa Hermawan',
                'nisn' => '2023203009',
                'tahun' => 2023,
                'no_hp_wali' => '081231112218',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 9, RT 04 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ratih Dwi Lestari',
                'kelas_id' => 3,
            ],

            // =================== KELAS 4 (2022) ===================
            [
                'nama' => 'Azzam Ilman Mufid',
                'nisn' => '2022204001',
                'tahun' => 2022,
                'no_hp_wali' => '081231112219',
                'alamat_siswa' => 'Jl. Ampel Kembang No. 30, RT 03 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Gunawan Prasetyo',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Balqis Ulfiyatus Sholihah',
                'nisn' => '2022204002',
                'tahun' => 2022,
                'no_hp_wali' => '081231112220',
                'alamat_siswa' => 'Jl. Sasak No. 81, RT 06 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Sulastri Dewi Utami',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Ghanira Zahrany Joycelyn',
                'nisn' => '2022204003',
                'tahun' => 2022,
                'no_hp_wali' => '081231112221',
                'alamat_siswa' => 'Jl. Petukangan No. 5, RT 02 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Heru Cahyono',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Husin Syarif Aljufri',
                'nisn' => '2022204004',
                'tahun' => 2022,
                'no_hp_wali' => '081231112222',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 55, RT 05 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rofiq Abdul Majid',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Muhammad Abidzar Ubaidillah',
                'nisn' => '2022204005',
                'tahun' => 2022,
                'no_hp_wali' => '081231112223',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 37, RT 03 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nur Azizah Mulyani',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Muhammad Azka Al Latif',
                'nisn' => '2022204006',
                'tahun' => 2022,
                'no_hp_wali' => '081231112224',
                'alamat_siswa' => 'Jl. Nyamplungan No. 66, RT 07 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Widya Kartika Sari',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Muhammad Dzikri As\'Syafin',
                'nisn' => '2022204007',
                'tahun' => 2022,
                'no_hp_wali' => '081231112225',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 24, RT 04 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Alfan Nurhidayat',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Sabrina Alesha Humairoh',
                'nisn' => '2022204008',
                'tahun' => 2022,
                'no_hp_wali' => '081231112226',
                'alamat_siswa' => 'Jl. Sasak No. 17, RT 01 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Lina Wulandari',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Sayyidah Tsania Mukhbita',
                'nisn' => '2022204009',
                'tahun' => 2022,
                'no_hp_wali' => '081231112227',
                'alamat_siswa' => 'Jl. Petukangan No. 73, RT 06 / RW 08, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rahmat Hidayat Anshori',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Muhammad Zainal Effendi',
                'nisn' => '2022204010',
                'tahun' => 2022,
                'no_hp_wali' => '081231112228',
                'alamat_siswa' => 'Jl. Nyamplungan No. 19, RT 02 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Siti Rahmah Lestari',
                'kelas_id' => 4,
            ],
            [
                'nama' => 'Abdul Hamid',
                'nisn' => '2021205001',
                'tahun' => 2021,
                'no_hp_wali' => '081231112229',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 21, RT 04 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Slamet Hariyanto',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Aurellia Citra Siswoyo',
                'nisn' => '2021205002',
                'tahun' => 2021,
                'no_hp_wali' => '081231112230',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 12, RT 01 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Dwi Kartika Ningrum',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Ali',
                'nisn' => '2021205003',
                'tahun' => 2021,
                'no_hp_wali' => '081231112231',
                'alamat_siswa' => 'Jl. Sasak No. 31, RT 03 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Mochammad Suroso Hadi',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Az-Zahra Safira Firdaus',
                'nisn' => '2021205004',
                'tahun' => 2021,
                'no_hp_wali' => '081231112232',
                'alamat_siswa' => 'Jl. Petukangan No. 44, RT 07 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Yuni Sri Rahayu',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Farhana',
                'nisn' => '2021205005',
                'tahun' => 2021,
                'no_hp_wali' => '081231112233',
                'alamat_siswa' => 'Jl. Nyamplungan No. 90, RT 02 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ahmad Teguh Santoso',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Khadijah',
                'nisn' => '2021205006',
                'tahun' => 2021,
                'no_hp_wali' => '081231112234',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 63, RT 05 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Wahyu Mustakim',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'M. Aufaa Al Faroh Fauzi',
                'nisn' => '2021205007',
                'tahun' => 2021,
                'no_hp_wali' => '081231112235',
                'alamat_siswa' => 'Jl. Ampel Suci No. 18, RT 03 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Cahyo Prasetyo Nugroho',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'M. Salman AlFarizi',
                'nisn' => '2021205008',
                'tahun' => 2021,
                'no_hp_wali' => '081231112236',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 22, RT 01 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rini Astutik Setyaningsih',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Muhammad Haidar Mumtaz',
                'nisn' => '2021205009',
                'tahun' => 2021,
                'no_hp_wali' => '081231112237',
                'alamat_siswa' => 'Jl. Sasak No. 71, RT 07 / RW 08, Kel. Ampel, Surabaya',
                'nama_wali' => 'Agus Supriyadi',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Muhammad Jalalludin Akbar Arifin',
                'nisn' => '2021205010',
                'tahun' => 2021,
                'no_hp_wali' => '081231112238',
                'alamat_siswa' => 'Jl. Petukangan No. 97, RT 04 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Dewi Maharani Yuliana',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Nadya Shafira Ahmad',
                'nisn' => '2021205011',
                'tahun' => 2021,
                'no_hp_wali' => '081231112239',
                'alamat_siswa' => 'Jl. Nyamplungan No. 50, RT 06 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rizal Abdurrahman',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Nisa\'ul Latifah',
                'nisn' => '2021205012',
                'tahun' => 2021,
                'no_hp_wali' => '081231112240',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 28, RT 02 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nur Aisyah Putri',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Nuwairal Muna',
                'nisn' => '2021205013',
                'tahun' => 2021,
                'no_hp_wali' => '081231112241',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 15, RT 03 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Hari Purnomo Widodo',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Obed Gahtan',
                'nisn' => '2021205014',
                'tahun' => 2021,
                'no_hp_wali' => '081231112242',
                'alamat_siswa' => 'Jl. Ampel Kembang No. 63, RT 04 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rohani Kusuma Dewi',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Rafa Maulana',
                'nisn' => '2021205015',
                'tahun' => 2021,
                'no_hp_wali' => '081231112243',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 33, RT 05 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Joni Setyawan',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Rayyan Fahmi Bahasuan',
                'nisn' => '2021205016',
                'tahun' => 2021,
                'no_hp_wali' => '081231112244',
                'alamat_siswa' => 'Jl. Ampel Suci No. 91, RT 02 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Siti Marfuah Rahayu',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Sana Amira',
                'nisn' => '2021205017',
                'tahun' => 2021,
                'no_hp_wali' => '081231112245',
                'alamat_siswa' => 'Jl. Sasak No. 10, RT 06 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Cahyadi Wibisono',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Safina Nur Az Zahra',
                'nisn' => '2021205018',
                'tahun' => 2021,
                'no_hp_wali' => '081231112246',
                'alamat_siswa' => 'Jl. Petukangan No. 41, RT 03 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Fitri Handayani',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Muhammad Adit Syahputra',
                'nisn' => '2021205019',
                'tahun' => 2021,
                'no_hp_wali' => '081231112247',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 88, RT 01 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Bambang Tri Susilo',
                'kelas_id' => 5,
            ],
            [
                'nama' => 'Maldini Ahmad Mubarok',
                'nisn' => '2021205020',
                'tahun' => 2021,
                'no_hp_wali' => '081231112248',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 39, RT 06 / RW 08, Kel. Ampel, Surabaya',
                'nama_wali' => 'Herlina Widjayanti',
                'kelas_id' => 5,
            ],

            // =================== KELAS 6 (2020) ===================
            [
                'nama' => 'Achmad Maziz Chamdani',
                'nisn' => '2020206001',
                'tahun' => 2020,
                'no_hp_wali' => '081231112249',
                'alamat_siswa' => 'Jl. Nyamplungan No. 16, RT 02 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Gunawan Adi Putra',
                'kelas_id' => 6,
            ],
            [
                'nama' => 'Akifa Naila Rifda',
                'nisn' => '2020206002',
                'tahun' => 2020,
                'no_hp_wali' => '081231112250',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 74, RT 04 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Siti Nurjanah Lestari',
                'kelas_id' => 6,
            ],
            [
                'nama' => 'Dzaky Almair Jamil',
                'nisn' => '2020206003',
                'tahun' => 2020,
                'no_hp_wali' => '081231112251',
                'alamat_siswa' => 'Jl. Petukangan No. 17, RT 01 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rifky Budi Santosa',
                'kelas_id' => 6,
            ],
            [
                'nama' => 'Habibah Nurul Istianah',
                'nisn' => '2020206004',
                'tahun' => 2020,
                'no_hp_wali' => '081231112252',
                'alamat_siswa' => 'Jl. Sasak No. 72, RT 03 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Lia Hartati Widyaningrum',
                'kelas_id' => 6,
            ],
            [
                'nama' => 'Moch Pandji Putra Krishna',
                'nisn' => '2020206005',
                'tahun' => 2020,
                'no_hp_wali' => '081231112253',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 19, RT 01 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Santoso Murjiono',
                'kelas_id' => 6,
            ],
            [
                'nama' => 'Muhammad Ziyad Al-Fatih',
                'nisn' => '2020206006',
                'tahun' => 2020,
                'no_hp_wali' => '081231112254',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 14, RT 06 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nur Aini Kartikasari',
                'kelas_id' => 6,
            ],
            [
                'nama' => 'Raihan Nur Najmi',
                'nisn' => '2020206007',
                'tahun' => 2020,
                'no_hp_wali' => '081231112255',
                'alamat_siswa' => 'Jl. Ampel Suci No. 60, RT 02 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Taufiq Hidayatullah',
                'kelas_id' => 6,
            ],
            [
                'nama' => 'M. Irfan Al-Hakim',
                'nisn' => '2020206008',
                'tahun' => 2020,
                'no_hp_wali' => '081231112256',
                'alamat_siswa' => 'Jl. Sasak No. 55, RT 04 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Wahyu Eka Saputra',
                'kelas_id' => 6,
            ],
        ]);
    }
}
