<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaTkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('siswa_tk')->delete();  
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('siswa_tk')->insert([

            // =================== KELOMPOK KB (kelas_id = 3) ===================
            [
                'nama' => 'M. ARSYADHITA ADNAN',
                'id_tk' => '2025301001',
                'tahun' => 2025,
                'no_hp_wali' => '082311942381',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 18, RT 02 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ahmad Rizky Firmansyah',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'M. FAUZAN',
                'id_tk' => '2025301002',
                'tahun' => 2025,
                'no_hp_wali' => '081553029441',
                'alamat_siswa' => 'Jl. Nyamplungan No. 44, RT 04 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Bambang Tri Hidayat',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'HUSAIN BARADJA',
                'id_tk' => '2025301003',
                'tahun' => 2025,
                'no_hp_wali' => '085837115902',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 27, RT 01 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Siti Nurjanah Rahmawati',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'AMINAH SYAFIYAH RABBANI',
                'id_tk' => '2025301004',
                'tahun' => 2025,
                'no_hp_wali' => '089674441239',
                'alamat_siswa' => 'Jl. Sasak No. 71, RT 03 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ratna Dewi Kartikasari',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'AISYATUL MUNAWAROH',
                'id_tk' => '2025301005',
                'tahun' => 2025,
                'no_hp_wali' => '082255419771',
                'alamat_siswa' => 'Jl. Ampel Suci No. 32, RT 05 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nur Kholifah Setyaningsih',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'M. DAFFA AINURROSI',
                'id_tk' => '2025301006',
                'tahun' => 2025,
                'no_hp_wali' => '088233017294',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 9, RT 01 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Eko Wahyudi Santoso',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'HANNA HUMAIROH BUSTOMI',
                'id_tk' => '2025301007',
                'tahun' => 2025,
                'no_hp_wali' => '081334822519',
                'alamat_siswa' => 'Jl. Petukangan No. 55, RT 03 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Lilis Astutik Pertiwi',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'ABDILLAH NAZIM NUR HAQQIQI',
                'id_tk' => '2025301008',
                'tahun' => 2025,
                'no_hp_wali' => '087755139204',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 21, RT 04 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Hariyanto Prasetyo',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'BILGIS HUMAIRA',
                'id_tk' => '2025301009',
                'tahun' => 2025,
                'no_hp_wali' => '085732991500',
                'alamat_siswa' => 'Jl. Ampel Kembang No. 14, RT 02 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Yani Fitri Arumsari',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'NARENDRA PRADIPTA AHNAF',
                'id_tk' => '2025301010',
                'tahun' => 2025,
                'no_hp_wali' => '081359992754',
                'alamat_siswa' => 'Jl. Gubah No. 30, RT 06 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rudi Hartono Wijaya',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'M.AZMI ROBITHUL HAQ',
                'id_tk' => '2025301011',
                'tahun' => 2025,
                'no_hp_wali' => '082397141280',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 10, RT 03 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Slamet Widodo Utomo',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'SAHILA',
                'id_tk' => '2025301012',
                'tahun' => 2025,
                'no_hp_wali' => '085752200471',
                'alamat_siswa' => 'Jl. Sasak No. 56, RT 01 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Kartini Astuti Pramudita',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'GIBRAN HABIBI ALFARIZQI',
                'id_tk' => '2025301013',
                'tahun' => 2025,
                'no_hp_wali' => '089667315820',
                'alamat_siswa' => 'Jl. Nyamplungan No. 11, RT 02 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rudi Setiawan Putro',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'M. ZAFRI EL SYADID',
                'id_tk' => '2025301014',
                'tahun' => 2025,
                'no_hp_wali' => '081233019941',
                'alamat_siswa' => 'Jl. Ampel Kembang No. 22, RT 05 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nurhayati Wulandari',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'M. ARSYADANI FAHIMAL MERTADO',
                'id_tk' => '2025301015',
                'tahun' => 2025,
                'no_hp_wali' => '087722511884',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 52, RT 07 / RW 08, Kel. Ampel, Surabaya',
                'nama_wali' => 'Didik Kurniawan Saputra',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'M. HASAN NABIL BAWASIR',
                'id_tk' => '2025301016',
                'tahun' => 2025,
                'no_hp_wali' => '082341559120',
                'alamat_siswa' => 'Jl. Ampel Suci No. 17, RT 03 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nanang Suwito Prasetyo',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'M. THAUFAL AUSY',
                'id_tk' => '2025301017',
                'tahun' => 2025,
                'no_hp_wali' => '085739218432',
                'alamat_siswa' => 'Jl. Petukangan No. 70, RT 06 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Arif Sudarmono',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'NAJWA ARBHANI YUSRO',
                'id_tk' => '2025301018',
                'tahun' => 2025,
                'no_hp_wali' => '089665314881',
                'alamat_siswa' => 'Jl. Sasak No. 22, RT 04 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Lilis Pramudiyani',
                'kelas_id' => 3,
            ],
            [
                'nama' => 'HASAN FATIH ALHADAD',
                'id_tk' => '2025301019',
                'tahun' => 2025,
                'no_hp_wali' => '081299731182',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 33, RT 01 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Faisal Arif Rahmansyah',
                'kelas_id' => 3,
            ],

            // =================== KELOMPOK A (kelas_id = 1) ===================
            [
                'nama' => 'AHMAD GANDHI RAFISQ',
                'id_tk' => '2025102001',
                'tahun' => 2025,
                'no_hp_wali' => '082241198552',
                'alamat_siswa' => 'Jl. Nyamplungan No. 27, RT 01 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Slamet Dwi Hartono',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'AISYAH NUHA ZAHRA',
                'id_tk' => '2025102002',
                'tahun' => 2025,
                'no_hp_wali' => '081556297744',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 44, RT 02 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Siti Mawaddah Munawaroh',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'ALVINO DAFFA MUWAFFAQ',
                'id_tk' => '2025102003',
                'tahun' => 2025,
                'no_hp_wali' => '087722445913',
                'alamat_siswa' => 'Jl. Sasak No. 31, RT 03 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Bagus Prayogo Hidayat',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'ARUMI SHANUM RIZALDIN',
                'id_tk' => '2025102004',
                'tahun' => 2025,
                'no_hp_wali' => '082299315671',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 55, RT 04 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rizal Muttaqin Santoso',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'HUMAIRA ALI SALIM',
                'id_tk' => '2025102005',
                'tahun' => 2025,
                'no_hp_wali' => '089662140299',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 14, RT 01 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Niken Lestari Pratiwi',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'MAULANA NAUFAL RAFIQI',
                'id_tk' => '2025102006',
                'tahun' => 2025,
                'no_hp_wali' => '081245881301',
                'alamat_siswa' => 'Jl. Petukangan No. 51, RT 05 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ahmad Choirul Nasir',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'M. BINTANG FARREL PARRAS',
                'id_tk' => '2025102007',
                'tahun' => 2025,
                'no_hp_wali' => '082233990544',
                'alamat_siswa' => 'Jl. Sasak No. 60, RT 04 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Dedi Purwanto',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'M. ALFINE DWI RAMDHANI',
                'id_tk' => '2025102008',
                'tahun' => 2025,
                'no_hp_wali' => '085739229011',
                'alamat_siswa' => 'Jl. Nyamplungan Gg 3 No. 8, RT 06 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Tri Anggraini Setyawati',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'M. RAJA AL- AYYUBI',
                'id_tk' => '2025102009',
                'tahun' => 2025,
                'no_hp_wali' => '081337922150',
                'alamat_siswa' => 'Jl. Ampel Kembang No. 31, RT 05 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Eka Julianto Saputro',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'M. SAUQI AMMAN',
                'id_tk' => '2025102010',
                'tahun' => 2025,
                'no_hp_wali' => '089611559224',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 78, RT 03 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Nadya Setyorini',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'RAFIQAH NAYLA HUSNA',
                'id_tk' => '2025102011',
                'tahun' => 2025,
                'no_hp_wali' => '087873301118',
                'alamat_siswa' => 'Jl. Ampel Suci No. 11, RT 01 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Sri Rahayu Prameswari',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'M. RAINER IVANDER CHOW',
                'id_tk' => '2025102012',
                'tahun' => 2025,
                'no_hp_wali' => '081294411732',
                'alamat_siswa' => 'Jl. Sasak No. 82, RT 04 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Hari Prasetyo Adnan',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'NUR SYAFIRA',
                'id_tk' => '2025102013',
                'tahun' => 2025,
                'no_hp_wali' => '082299511807',
                'alamat_siswa' => 'Jl. Petukangan No. 66, RT 02 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Dewi Maharani Astutik',
                'kelas_id' => 1,
            ],
            [
                'nama' => 'RAYYAN YUSUF',
                'id_tk' => '2025102014',
                'tahun' => 2025,
                'no_hp_wali' => '085839411209',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 29, RT 03 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Fauzan Ali Ridho',
                'kelas_id' => 1,
            ],

            // =================== KELOMPOK B (kelas_id = 2) ===================
            [
                'nama' => 'ABU BAKAR SHADIQ',
                'id_tk' => '2025203001',
                'tahun' => 2024,
                'no_hp_wali' => '082134992511',
                'alamat_siswa' => 'Jl. Nyamplungan No. 90, RT 01 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ahmad Kurniawan Saputra',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'AHMAD EMRAN DENIZ ARSHAVIN',
                'id_tk' => '2024203002',
                'tahun' => 2024,
                'no_hp_wali' => '089632244881',
                'alamat_siswa' => 'Jl. Sasak No. 12, RT 04 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Rina Anggraeni Dewanti',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'M. KEISYAM',
                'id_tk' => '2024203003',
                'tahun' => 2024,
                'no_hp_wali' => '081334112709',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 34, RT 02 / RW 01, Kel. Ampel, Surabaya',
                'nama_wali' => 'Dimas Yulianto Putro',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'AMINAH MUCHSIN',
                'id_tk' => '2024203004',
                'tahun' => 2024,
                'no_hp_wali' => '087722593114',
                'alamat_siswa' => 'Jl. Petukangan No. 80, RT 06 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Sari Hartati Lestyaningrum',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'AHMAD ADNAN BAIHAQI',
                'id_tk' => '2024203005',
                'tahun' => 2024,
                'no_hp_wali' => '082214439950',
                'alamat_siswa' => 'Jl. Ampel Masjid No. 81, RT 03 / RW 06, Kel. Ampel, Surabaya',
                'nama_wali' => 'Muhammad Rizal Basuki',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'FATIMAH AZZAHRA',
                'id_tk' => '2024203006',
                'tahun' => 2024,
                'no_hp_wali' => '085631904225',
                'alamat_siswa' => 'Jl. Gubah No. 7, RT 01 / RW 02, Kel. Ampel, Surabaya',
                'nama_wali' => 'Wiwik Novitasari',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'M. RO\'UF',
                'id_tk' => '2024203007',
                'tahun' => 2024,
                'no_hp_wali' => '081592201814',
                'alamat_siswa' => 'Jl. KH Mas Mansyur No. 53, RT 02 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Bayu Tri Handoko',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'M. HAIDAR',
                'id_tk' => '2024203008',
                'tahun' => 2024,
                'no_hp_wali' => '089782331500',
                'alamat_siswa' => 'Jl. Ampel Suci No. 23, RT 03 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Cahyo Ari Prasetyo',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'MUHAMMAD AL-HABSYI',
                'id_tk' => '2024203009',
                'tahun' => 2024,
                'no_hp_wali' => '082399411284',
                'alamat_siswa' => 'Jl. Nyamplungan No. 55, RT 01 / RW 03, Kel. Ampel, Surabaya',
                'nama_wali' => 'Johan Dwi Hartono',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'SYAIKHAH SULTHANAH',
                'id_tk' => '2024203010',
                'tahun' => 2024,
                'no_hp_wali' => '087833192041',
                'alamat_siswa' => 'Jl. Sasak No. 43, RT 06 / RW 07, Kel. Ampel, Surabaya',
                'nama_wali' => 'Siti Aisyah Paramita',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'KINARA',
                'id_tk' => '2024203011',
                'tahun' => 2024,
                'no_hp_wali' => '085772541009',
                'alamat_siswa' => 'Jl. Ampel Kebun No. 59, RT 03 / RW 04, Kel. Ampel, Surabaya',
                'nama_wali' => 'Ardian Kusumayadi',
                'kelas_id' => 2,
            ],
            [
                'nama' => 'SHAVA',
                'id_tk' => '2024203012',
                'tahun' => 2024,
                'no_hp_wali' => '081290114922',
                'alamat_siswa' => 'Jl. KH Moh Kholil No. 12, RT 02 / RW 05, Kel. Ampel, Surabaya',
                'nama_wali' => 'Mega Yuliana Putri',
                'kelas_id' => 2,
            ],
        ]);
    }
}
